// Copyright (c) 2025 Uncommon Goods LLC
// SPDX-License-Identifier: MIT

/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.12.1/userguide/multi_project_builds.html in the Gradle documentation.
 */

pluginManagement {
  repositories {
    gradlePluginPortal()
  }
}

plugins {
  // Apply the foojay-resolver plugin to allow automatic download of JDKs
  id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

rootProject.name = "tugboat"

include(
  "engine",
  "hooks",
  "ports",
  "bridge",
  "xo"
)

// Configure project names
project(":engine").name = "tugboat-engine"
project(":hooks").name = "tugboat-hooks"
project(":ports").name = "tugboat-ports"
project(":bridge").name = "tugboat-bridge"
project(":xo").name = "tugboat-xo"

// ---------------------------------------------------------------------------
// Adapters.
//
// Every directory under adapters/ holding a build script is an adapter module,
// included as :adapters:tugboat-<dir>. Dropping a module in is all it takes --
// no include() line here and no dependency line in a host build script, which
// is what keeps a private adapter from requiring changes to any tracked file.
// Hosts then depend on every child of :adapters rather than naming them (see
// bridge/build.gradle.kts and xo/build.gradle.kts).
//
// Probe for each module's build script, not merely its directory: a checkout
// that once had a module keeps a stale build/ output directory behind after the
// sources are removed, and a bare `isDirectory` check treats that as "present".
// The module then configures with no sources and the hosts take an
// implementation() dependency on an empty jar. adapters/build/ -- the aggregate
// project's own output directory -- is skipped for the same reason.
// ---------------------------------------------------------------------------

fun hasBuildScript(dir: java.io.File) =
  dir.resolve("build.gradle.kts").isFile || dir.resolve("build.gradle").isFile

val adapterDirs = settingsDir.resolve("adapters").listFiles()
  ?.filter { it.isDirectory && hasBuildScript(it) }
  ?.sortedBy { it.name }
  .orEmpty()

// Some adapters wrap a generated vendor SDK that lives as a sibling module at
// the repo root under the same name (ESW, Parsel). Those SDKs are not tracked in
// version control, so take the pair or neither: the adapter does not build
// without its SDK. An adapter with no root-level namesake -- the normal case,
// and the case for any third-party adapter -- is taken unconditionally.
val adapterNames = adapterDirs
  .map { it.name }
  .filter { name ->
    val companion = settingsDir.resolve(name)
    !companion.isDirectory || hasBuildScript(companion)
  }

// Include everything first, then rename, so no rename can affect how a later
// include resolves its path.
for (name in adapterNames) {
  if (settingsDir.resolve(name).isDirectory) {
    include(name)
  }
  include("adapters:$name")
}
for (name in adapterNames) {
  project(":adapters:$name").name = "tugboat-$name"
}

val adapterProjects = adapterNames.map { ":adapters:tugboat-$it" }

// playground is a scratch/manual-test harness. Like the vendor modules it is not
// tracked in version control (see .gitignore), so probe for it the same way
// rather than assuming a clone has it. It also constructs the ESW and Parsel
// clients directly, so it needs both of those adapters on disk as well.
if (hasBuildScript(settingsDir.resolve("playground")) &&
  adapterProjects.containsAll(
    listOf(":adapters:tugboat-esw-package", ":adapters:tugboat-parsel")
  )
) {
  include("playground")
}
